Repository Roave/BackwardCompatibilityCheck, pull requests merged in 2020-02, with the labels that each got.

#178 s/`deploy.api_key.secure`/`deploy.api_key`
  .travis.yml
Labels: bug

#197 Fix Travis builds
  .travis.yml
  bin/roave-backward-compatibility-check.php
  composer.json
  composer.lock
  phpstan.neon.dist
  test/unit/ChangesTest.php
  test/unit/Command/AssertBackwardsCompatibleTest.php
  test/unit/DetectChanges/BCBreak/ClassBased/AncestorRemovedTest.php
  test/unit/DetectChanges/BCBreak/ClassBased/ClassBecameAbstractTest.php
  test/unit/DetectChanges/BCBreak/ClassBased/ClassBecameFinalTest.php
  test/unit/DetectChanges/BCBreak/ClassBased/ClassBecameInterfaceTest.php
  test/unit/DetectChanges/BCBreak/ClassBased/ClassBecameInternalTest.php
  test/unit/DetectChanges/BCBreak/ClassBased/ClassBecameTraitTest.php
  test/unit/DetectChanges/BCBreak/ClassBased/ConstantRemovedTest.php
  test/unit/DetectChanges/BCBreak/ClassBased/MethodRemovedTest.php
  test/unit/DetectChanges/BCBreak/ClassBased/PropertyRemovedTest.php
  test/unit/DetectChanges/BCBreak/ClassConstantBased/ClassConstantValueChangedTest.php
  test/unit/DetectChanges/BCBreak/ClassConstantBased/ClassConstantVisibilityReducedTest.php
  test/unit/DetectChanges/BCBreak/FunctionBased/FunctionBecameInternalTest.php
  test/unit/DetectChanges/BCBreak/FunctionBased/ParameterByReferenceChangedTest.php
  test/unit/DetectChanges/BCBreak/FunctionBased/ParameterDefaultValueChangedTest.php
  test/unit/DetectChanges/BCBreak/FunctionBased/ParameterTypeChangedTest.php
  test/unit/DetectChanges/BCBreak/FunctionBased/ParameterTypeContravarianceChangedTest.php
  test/unit/DetectChanges/BCBreak/FunctionBased/RequiredParameterAmountIncreasedTest.php
  test/unit/DetectChanges/BCBreak/FunctionBased/ReturnTypeByReferenceChangedTest.php
  test/unit/DetectChanges/BCBreak/FunctionBased/ReturnTypeChangedTest.php
  test/unit/DetectChanges/BCBreak/FunctionBased/ReturnTypeCovarianceChangedTest.php
  test/unit/DetectChanges/BCBreak/InterfaceBased/AncestorRemovedTest.php
  test/unit/DetectChanges/BCBreak/InterfaceBased/InterfaceBecameClassTest.php
  test/unit/DetectChanges/BCBreak/InterfaceBased/InterfaceBecameTraitTest.php
  test/unit/DetectChanges/BCBreak/InterfaceBased/MethodAddedTest.php
  test/unit/DetectChanges/BCBreak/MethodBased/MethodBecameFinalTest.php
  test/unit/DetectChanges/BCBreak/MethodBased/MethodConcretenessChangedTest.php
  test/unit/DetectChanges/BCBreak/MethodBased/MethodScopeChangedTest.php
  test/unit/DetectChanges/BCBreak/MethodBased/MethodVisibilityReducedTest.php
  test/unit/DetectChanges/BCBreak/PropertyBased/PropertyBecameInternalTest.php
  test/unit/DetectChanges/BCBreak/PropertyBased/PropertyDefaultValueChangedTest.php
  test/unit/DetectChanges/BCBreak/PropertyBased/PropertyDocumentedTypeChangedTest.php
  test/unit/DetectChanges/BCBreak/PropertyBased/PropertyScopeChangedTest.php
  test/unit/DetectChanges/BCBreak/PropertyBased/PropertyVisibilityReducedTest.php
  test/unit/DetectChanges/BCBreak/TraitBased/TraitBecameClassTest.php
  test/unit/DetectChanges/BCBreak/TraitBased/TraitBecameInterfaceTest.php
  test/unit/Formatter/ReflectionPropertyNameTest.php
  test/unit/Git/PickLastMinorVersionFromCollectionTest.php
  test/unit/SourceLocator/StaticClassMapSourceLocatorTest.php
  test/unit/Support/ArrayHelpersTest.php
  test/unit/TypeRestriction.php
Labels: bug

#198 Do not skip cleanup when deploying
  .travis.yml
Labels: bug

#199 #179 bump `nikolaposa/version` dependency to `4.0.0`
  composer.json
  composer.lock
  src/Command/AssertBackwardsCompatible.php
  src/Git/GetVersionCollection.php
  src/Git/GetVersionCollectionFromGitRepository.php
  src/Git/PickLastMinorVersionFromCollection.php
  src/Git/PickVersionFromVersionCollection.php
  test/unit/Command/AssertBackwardsCompatibleTest.php
  test/unit/Git/GetVersionCollectionFromGitRepositoryTest.php
  test/unit/Git/PickLastMinorVersionFromCollectionTest.php
Labels: bc break, enhancement

#201 Update github action example
  README.md
Labels: enhancement
