Repository Roave/BackwardCompatibilityCheck, pull requests merged in 2021-11, with the labels that each got.

#295 Replaced at() matcher with onConsecutive stub
  test/unit/Command/AssertBackwardsCompatibleTest.php
  test/unit/Formatter/SymfonyConsoleTextFormatterTest.php
Labels: enhancement, dependencies

#319 Added option for `--install-development-dependencies`
  psalm.xml
  src/Command/AssertBackwardsCompatible.php
  src/LocateDependencies/LocateDependencies.php
  src/LocateDependencies/LocateDependenciesViaComposer.php
  test/unit/Command/AssertBackwardsCompatibleTest.php
  test/unit/LocateDependencies/LocateDependenciesViaComposerTest.php
Labels: enhancement, bc break, hacktoberfest-accepted

#322 `totallyTyped="true"` in psalm configuration
  composer.json
  composer.lock
  infection.json.dist
  psalm.xml
  src/Changes.php
  src/CompareClasses.php
  src/DetectChanges/BCBreak/ClassBased/ConstantChanged.php
  src/DetectChanges/BCBreak/ClassBased/MethodChanged.php
  src/DetectChanges/BCBreak/ClassBased/MethodRemoved.php
  src/DetectChanges/BCBreak/ClassBased/MultipleChecksOnAClass.php
  src/DetectChanges/BCBreak/ClassBased/PropertyChanged.php
  src/DetectChanges/BCBreak/ClassConstantBased/MultipleChecksOnAClassConstant.php
  src/DetectChanges/BCBreak/FunctionBased/MultipleChecksOnAFunction.php
  src/DetectChanges/BCBreak/FunctionBased/ParameterTypeChanged.php
  src/DetectChanges/BCBreak/InterfaceBased/MultipleChecksOnAnInterface.php
  src/DetectChanges/BCBreak/MethodBased/MultipleChecksOnAMethod.php
  src/DetectChanges/BCBreak/PropertyBased/MultipleChecksOnAProperty.php
  src/DetectChanges/BCBreak/TraitBased/MultipleChecksOnATrait.php
  src/Factory/ComposerInstallationReflectorFactory.php
  src/Factory/DirectoryReflectorFactory.php
  src/Git/GetVersionCollectionFromGitRepository.php
  src/Git/GitCheckoutRevisionToTemporaryPath.php
  src/Git/PickLastMinorVersionFromCollection.php
  src/LocateDependencies/LocateDependenciesViaComposer.php
  test/unit/ChangesTest.php
  test/unit/Command/AssertBackwardsCompatibleTest.php
  test/unit/Factory/ComposerInstallationReflectorFactoryTest.php
  test/unit/Git/GetVersionCollectionFromGitRepositoryTest.php
  test/unit/Git/PickLastMinorVersionFromCollectionTest.php
  test/unit/LocateDependencies/LocateDependenciesViaComposerTest.php
Labels: enhancement

#340 Add testsand implementation for property types changing from docblock-only to native type
  src/DetectChanges/BCBreak/PropertyBased/PropertyDocumentedTypeChanged.php
  test/unit/DetectChanges/BCBreak/PropertyBased/PropertyDocumentedTypeChangedTest.php
Labels: enhancement
