Repository Roave/BackwardCompatibilityCheck, pull requests merged in 2022-10, with the labels that each got.

#643 Support PHP 8.2, drop support for PHP 8.0, upgrade to `azjezz/psl:^2`
  .github/workflows/continuous-integration.yml
  bin/roave-backward-compatibility-check.php
  composer.json
  composer.lock
  infection.json.dist
  src/Command/AssertBackwardsCompatible.php
  src/Formatter/MarkdownPipedToSymfonyConsoleFormatter.php
  src/Git/CheckedOutRepository.php
  src/Git/GetVersionCollectionFromGitRepository.php
  src/Git/GitCheckoutRevisionToTemporaryPath.php
  src/Git/PickLastMinorVersionFromCollection.php
  src/Git/Revision.php
  src/SourceLocator/StaticClassMapSourceLocator.php
  test/e2e/Command/AssertBackwardsCompatibleTest.php
  test/unit/ChangesTest.php
  test/unit/Command/AssertBackwardsCompatibleTest.php
  test/unit/DetectChanges/BCBreak/ClassConstantBased/ClassConstantValueChangedTest.php
  test/unit/DetectChanges/BCBreak/ClassConstantBased/ClassConstantVisibilityReducedTest.php
  test/unit/DetectChanges/Variance/TypeIsContravariantTest.php
  test/unit/DetectChanges/Variance/TypeIsCovariantTest.php
  test/unit/Formatter/GithubActionsFormatterTest.php
  test/unit/Git/GetVersionCollectionFromGitRepositoryTest.php
  test/unit/Git/GitCheckoutRevisionToTemporaryPathTest.php
  test/unit/Git/PickLastMinorVersionFromCollectionTest.php
  test/unit/Git/RevisionTest.php
  test/unit/LocateDependencies/LocateDependenciesViaComposerTest.php
  test/unit/SourceLocator/StaticClassMapSourceLocatorTest.php
Labels: enhancement

#657 Always cleanup the temporary directory in github actions formatter test even if the assertion fails.
  test/unit/Formatter/GithubActionsFormatterTest.php
Labels: bug

#654 Added junit formatter.
  src/Command/AssertBackwardsCompatible.php
  src/Formatter/JunitFormatter.php
  test/unit/Formatter/JunitFormatterTest.php
  test/unit/Formatter/junit.xsd
Labels: enhancement

#680 Upgrade all minor dependency versions to their latest and greatest
  composer.json
  composer.lock
  infection.json.dist
Labels: enhancement, dependencies
